prjemian/spec2nexus

- src/spec2nexus/data/usaxs-bluesky-specwritercallback.dat
- src/spec2nexus/plugins/apstools_specwriter_spec2nexus.py
- tests/__init__.py
- tests/test_md_apstools_specwriter.py
> plugin support for #MD control lines (apstools.SpecWriterCallback)

- .travis.yml
- CHANGES.rst
- src/spec2nexus/charts.py
- src/spec2nexus/plugin.py
- src/spec2nexus/plugins/spec_common_spec2nexus.py
- src/spec2nexus/spec.py
- tests/__init__.py
- tests/issue107.py
- tests/issue123.py
- tests/test_spec.py
- tests/test_specplot_gallery.py
> accept SPEC data files that do not have header section

- src/spec2nexus/_version.py
- src/spec2nexus/uxml/uxml_spec2nexus.py
- src/spec2nexus/writer.py
- versioneer.py
> resolve LGTM alerts

- .travis.yml
- src/spec2nexus/_requirements.py
- tests/test_requirements.py
> locate requirements file

- .travis.yml
- src/spec2nexus/_requirements.py
- src/spec2nexus/writer.py
- tests/test_requirements.py
- tests/test_writer.py
> writer: unit tests 

- .travis.yml
- src/spec2nexus/_requirements.py
- src/spec2nexus/eznx.py
- src/spec2nexus/plugins/uxml.xsd
- src/spec2nexus/writer.py
- tests/test_eznx.py
- tests/test_requirements.py
- tests/test_uxml.py
- tests/test_writer.py
> more unit tests for eznx

- CHANGES.rst
- src/spec2nexus/writer.py
- tests/test_writer.py
package release candidates for end-user installation and testing
> prep for release 2021.1.0

- CHANGES.rst
- tests/test_plugin.py
> fix test alerts per LGTM review

- src/spec2nexus/spec.py
- tests/test_spec.py
> spec: update_available property

- .gitignore
- CHANGES.rst
- src/spec2nexus/specplot_gallery.py
- tests/test_specplot_gallery.py
> specplot_gallery: replot shows all existing plots

- .travis.yml
- CHANGES.rst
- src/spec2nexus/spec.py
- src/spec2nexus/specplot_gallery.py
- tests/__init__.py
- tests/issue188.py
> merge continued lines in data file before parsing data

- src/spec2nexus/data/usaxs-bluesky-specwritercallback.dat
- src/spec2nexus/plugins/spec_common.py
- tests/__init__.py
- tests/issue216.py
fixes #216, makes the exception message more clear
> raise ValueError when #L and #N lines do not agree

- CHANGES.rst
- src/spec2nexus/plugins/spec_common.py
documentation and additional test (for single-space delimiter)
> 216 default labels

- .flake8
- .gitignore
- pytest.ini
- src/spec2nexus/spec.py
> optimize data file open time

- src/spec2nexus/plugins/spec_common.py
- src/spec2nexus/tests/test_spec.py
> test with MCA data

- src/spec2nexus/diffractometers.py
> answer question about singleton

- .github/workflows/unit-tests-pytest.yml
- README.md
- src/spec2nexus/__init__.py
> unit testing with Py3.10

- src/spec2nexus/nexus.py
> update the nexus module

- .github/workflows/unit-tests-pytest.yml
> upload code coverage in GH workflow

- .github/workflows/publish-docs.yml
- CHANGES.rst
- README.md
- docs/source/conf.py
- docs/source/extractSpecScan.rst
- docs/source/index.rst
- docs/source/supplied_plugins/apstools_specwriter.rst
- src/spec2nexus/__init__.py
- src/spec2nexus/extractSpecScan.py
- src/spec2nexus/nexus.py
- src/spec2nexus/specplot_gallery.py
> publish to GitHub pages

- .github/workflows/publish-docs.yml
- conda-recipe/meta.yaml
- docs/source/_static/pv_plugin.py
- docs/source/conf.py
- docs/source/how_to_write_plugin.rst
- docs/source/unit_testing.rst
- environment.yml
- requirements-dev.txt
- requirements.txt
- src/spec2nexus/eznx.py
- src/spec2nexus/plugins/XPCS.py
- src/spec2nexus/plugins/apstools_specwriter.py
- src/spec2nexus/plugins/fallback.py
- src/spec2nexus/plugins/spec_common.py
- src/spec2nexus/plugins/uim.py
- src/spec2nexus/plugins/unicat.py
- src/spec2nexus/plugins/uxml.py
- src/spec2nexus/tests/custom_plugins/process_only_plugin.py
- src/spec2nexus/tests/test_requirements.py
> review & revise package requirements

- .github/workflows/publish-docs.yml
- .gitignore
- docs/source/conf.py
- docs/source/index.rst
- requirements-dev.txt
> use furo HTML theme with Sphinx

- .gitignore
- README.md
- docs/source/api.rst
- docs/source/applications.rst
- docs/source/contents.rst
- docs/source/control_lines.rst
- docs/source/diffractometers.rst
- docs/source/example_data.rst
- docs/source/how_to_write_plugin.rst
- docs/source/howto.rst
- docs/source/index.rst
- docs/source/libraries.rst
- docs/source/nexus_layout/example_1d_scan.rst
- docs/source/plugin_core.rst
- docs/source/spec2nexus.rst
- docs/source/specplot_custom_scan_macro.rst
- docs/source/utils.rst
- setup.py
- src/spec2nexus/diffractometers.py
>  re-organize the documention

- CHANGES.rst
- docs/source/spec2nexus.rst
- src/spec2nexus/plugins/spec_common.py
- src/spec2nexus/tests/_core.py
- src/spec2nexus/tests/test_spec.py
> Support standard #R control line

- CHANGES.rst
- conda-recipe/run_test.py
- demo/usaxs_flyscan.py
- demo/usaxs_uascan.py
- docs/source/nexus_layout/general_tree.rst
- docs/source/nexus_layout/metadata.rst
- docs/source/nexus_layout/temperature.rst
- docs/source/specplot_custom_scan_macro.rst
- src/spec2nexus/diffractometers.py
- src/spec2nexus/plugins/spec_common.py
- src/spec2nexus/plugins/uxml.py
- src/spec2nexus/tests/test_diffractometers.py
- src/spec2nexus/tests/test_uxml.py
> resolve TODO & FIXME markers

- .github/workflows/unit-tests-pytest.yml
> use mamba in CI

- .github/workflows/publish-docs.yml
- CHANGES.rst
- docs/source/api.rst
- docs/source/conf.py
> Add spec module to API documentation page

- .github/workflows/publish-docs.yml
- docs/source/conf.py
- requirements.txt
> repair the documentation workflow

- .github/workflows/unit-tests-pytest.yml
- CHANGES.rst
- setup.cfg
> drop support for Python 3.7

- CHANGES.rst
- MANIFEST.in
- setup.cfg
> adjust the packaging for extra files

- CHANGES.rst
- spec2nexus/diffractometers.py
- spec2nexus/plugins/spec_common.py
- spec2nexus/tests/test_diffractometers.py
- spec2nexus/writer.py
Uses geometry when data file declares in file header, as written by SPEC standard macro.
- fix #300
> Recognize known geometry if stated in data file header.

- CHANGES.rst
- spec2nexus/plugins/spec_common.py
> Don't warn when truncation affects comparison of file epoch and scan epoch.

- CHANGES.rst
- spec2nexus/spec.py
- spec2nexus/tests/test_spec.py
> Expand recognition of SPEC data files to match more patterns

- .github/workflows/code.yml
- CHANGES.rst
- docs/source/conf.py
- pyproject.toml
> switch HTML to pydata sphinx theme

- CHANGES.rst
- spec2nexus/plugins/spec_common.py
> Change the logic
